### ISSUE TITLE
library(spatialLIBD)

### ISSUE THREAD

**Issue by cfyy** [LieberInstitute/spatialLIBD#16]
Hi,
when I want to "library(spatialLIBD)", It occurs the message:
Error: package or namespace load failed for ‘spatialLIBD’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
namespace ‘matrixStats’ 0.57.0 is already loaded, but >= 0.60.0 is required
but I have reinstall the matrixStats packages
could you please help me?

Thanks
Best

**Comment by lcolladotor** [comment]
Hi @cfyy,

If you run `packageVersion("matrixStats")` you will likely still have version 0.57.0 installed. That's assuming you tried to update it on the same R session you tried to load `spatialLIBD`. If that's the case, then R will have loadded `matrixStats`, and then if you tried to install it on the same R session, that installation would fail.

It's best to install R packages on a fresh R session without having loaded any packages. For that, make sure that you don't have any environments saved, because they could contain R objects that load R packages without you noticing it.

Best,
Leo

**Comment by cfyy** [comment]
Thank you!
