### ISSUE TITLE
Error when downloading the dataset

### ISSUE THREAD

**Issue by lero1005** [LieberInstitute/spatialLIBD#30]
Hi, I'm trying to run the R code "sce <- fetch_data(type = 'sce', eh = ehub)" as is written in the tutorial to access the processed data , but Error occurs when running the code.
The Error messages are stated as follows:
```
> sce <- fetch_data(type = 'sce', eh = ehub)
adding rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1'
Error in BiocFileCache::bfcrpath(bfc, url) : 
  not all 'rnames' found or unique.
此外: Warning messages:
1: download failed
  web resource path: ‘https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1’
  local file path: ‘/tmp/RtmpRP4ATx/BiocFileCache/1f495f32f384_Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata%3Fdl%3D1’
  reason: Timeout was reached: [www.dropbox.com] Connection timed out after 10000 milliseconds 
2: bfcadd() failed; resource removed
  rid: BFC3
  fpath: ‘https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1’
  reason: download failed 
3: In value[[3L]](cond) : 
trying to add rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1' produced error:
  bfcadd() failed; see warnings()
> spe <- fetch_data(type = "spe")
snapshotDate(): 2021-10-19
adding rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1'
Error in BiocFileCache::bfcrpath(bfc, url) : 
  not all 'rnames' found or unique.
此外: Warning messages:
1: download failed
  web resource path: ‘https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1’
  local file path: ‘/tmp/RtmpRP4ATx/BiocFileCache/1f497f0d458c_Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata%3Fdl%3D1’
  reason: Timeout was reached: [www.dropbox.com] Connection timed out after 10000 milliseconds 
2: bfcadd() failed; resource removed
  rid: BFC4
  fpath: ‘https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1’
  reason: download failed 
3: In value[[3L]](cond) : 
trying to add rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1' produced error:
  bfcadd() failed; see warnings()
```
So how can I get access to the processed data?

Thanks for your help!

**Comment by lcolladotor** [comment]
Hi @lero1005,

Thanks for using `spatialLIBD` and being interested in our work.

Hmm, can you post the reproducibility information? That is, `options(width = 120); sessioninfo::session_info()`. That will let me know what versions you are using. In any case, it seems like you are running into a connection timeout. Maybe something was wrong with Dropbox when you tried it. From your message, I see for example `https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1` which works on my browser if I copy-paste it. Maybe your internet connection is blocking Dropbox? In any case, try if you can access the data from the browser instead of through R.

Best,
Leo

**Comment by lero1005** [comment]
> 

Thank you for the reminder!  It is indeed the connection problem as you said, so I manually downloaded the data and placed it in the cache. Problem solved. Thanks again!

**Comment by soya-yaya** [comment]
Hello, I found I couldn't get whole data because of slow connection through Dropbox. Meanwhile, if I click on 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1', I just can acquire a part of data whose volume is 112B. How do I can get whole data?
Thank you for your response.

**Comment by soya-yaya** [comment]
Hello, I found I couldn't get whole data because of slow connection through Dropbox. Meanwhile, if I click on 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1', I just can acquire a part of data whose volume is 112B. How can I get whole data?
Thank you for your response.

**Comment by lcolladotor** [comment]
Hi @soya-yaya,

Thank you for your interest in our data. This feels like a new issue, instead of a continuation of the previous one.

It sounds like your WiFi (ISP or something along the way) is blocking access to Dropbox. Try accessing the data via Globus https://github.com/LieberInstitute/spatialLIBD?tab=readme-ov-file#raw-data.

Best,
Leo

**Comment by soya-yaya** [comment]
Hi, I have a simple question. 

After I download the data from 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1', where should I place it in? And how to use the data? Using the commend 'spe <- [fetch_data]' again?

the details of error as followed:
`> spe <- fetch_data(type = "spe")
snapshotDate(): 2023-10-24
adding rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1'
Error in BiocFileCache::bfcrpath(bfc, url) : 
  not all 'rnames' found or unique.
此外: Warning messages:
1: download failed
  web resource path: ‘https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1’
  local file path: ‘\Local/R/cache/R/BiocFileCache/82c44016941_Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata%3Fdl%3D1’
  reason: Timeout was reached: [www.dropbox.com] Failed to connect to www.dropbox.com port 443 after 10006 ms: Timeout was reached 
2: bfcadd() failed; resource removed
  rid: BFC10
  fpath: ‘https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1’
  reason: download failed 
3: In value[[3L]](cond) : 
trying to add rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1' produced error:
  bfcadd() failed; see warnings()`

Thank you for your response.

**Comment by lcolladotor** [comment]
Hi,

You seem to be having the same issue reported and resolved at https://github.com/LieberInstitute/spatialLIBD/issues/73#issuecomment-2016520542.

That is, for some reason you are not able to download the data from Dropbox directly with `BiocFileCache::bfcrpath()` (the function used internally by `spatialLIBD::fetch_data()`). You'll likely have to download the data manually using your web browser, though you could also try the `download.file()` option highlighted in the other issue.

Best,
Leo
