### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by carlosf79** [LieberInstitute/spatialLIBD#4]
Hello, I was trying to install the package, but apparently it is not available (R says that 'cannot open URL'). Also manually following links to Bioconductor does not lead to the proper page.
Do you have any suggestion?
Thanks!

**Comment by lcolladotor** [comment]
Hi @carlosf79,

21 days ago `spatialLIBD` was not available yet from Bioconductor since it was under revision. Since Bioconductor 3.11 was released last week, you should be able to install `spatialLIBD` with the stated instructions. While you can install the package directly from GitHub, we highly recommend that you install the package using `BiocManager` given the dependencies on other Bioconductor packages.

Best,
Leo
