### ISSUE TITLE
Want to download the full real data (spe) to use

### ISSUE THREAD

**Issue by zhang-TD** [LieberInstitute/spatialLIBD#45]
Hello!
I have the same problem as 'https://github.com/LieberInstitute/spatialLIBD/issues/35'.  And I found that the data 'https://www.dropbox.com/s/5ra9o8ku9iyyf70/sce_sub_for_vignette.Rdata?dl=1' was not intact. I want to analyze the full real data (spe). Could you please help me download the full data? 
Thank you very very much!

**Comment by lcolladotor** [comment]
Hi @zhang-TD,

Can you be a bit more specific? `spatialLIBD::fetch_data()` provides access to SPE objects from multiple studies. Do you want the data from Maynard, Collado-Torres, et al, 2021?

Best,
Leo

**Comment by soya-yaya** [comment]
Hello, I found I couldn't get whole data because of slow connection through Dropbox. Meanwhile, if I click on 'https://www.dropbox.com/s/5ra9o8ku9iyyf70/sce_sub_for_vignette.Rdata?dl=1', I just can acquire a part of data whose volume is 112B. How do I can get whole data?
Thank you for your response.
